import '../css/app.css';

const state = { token: localStorage.getItem('pointku_token'), user: JSON.parse(localStorage.getItem('pointku_user') || 'null'), page: location.hash.replace('#', '') || 'overview' };
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char]));
const role = () => state.user?.role?.nama_role || 'Pengguna';
const isRecorder = () => ['Guru BK', 'Guru Pelapor'].includes(role());

async function api(path, options = {}) {
    const response = await fetch(`/api${path}`, { ...options, headers: { Accept: 'application/json', ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(state.token ? { Authorization: `Bearer ${state.token}` } : {}), ...options.headers } });
    const data = await response.json().catch(() => ({}));
    if (response.status === 401) logout(false);
    if (!response.ok) throw new Error(data.message || Object.values(data.errors || {})[0]?.[0] || 'Permintaan tidak dapat diproses.');
    return data;
}

function logout(callApi = true) { if (callApi && state.token) api('/logout', { method: 'POST' }).catch(() => {}); localStorage.removeItem('pointku_token'); localStorage.removeItem('pointku_user'); state.token = null; state.user = null; render(); }

function render() { $('[data-view="login"]').classList.toggle('is-hidden', !!state.token && !!state.user); $('[data-view="application"]').classList.toggle('is-hidden', !(state.token && state.user)); if (state.token && state.user) { hydrateShell(); loadPage(); } }

function hydrateShell() {
    const firstName = state.user.nama_lengkap?.split(' ')[0] || 'Pengguna';
    $$('[data-user-name]').forEach((el) => el.textContent = state.user.nama_lengkap || 'Pengguna');
    $$('[data-user-role]').forEach((el) => el.textContent = role());
    $$('[data-user-initial]').forEach((el) => el.textContent = firstName.slice(0, 1).toUpperCase());
    $('#today-label').textContent = new Intl.DateTimeFormat('id-ID', { dateStyle: 'full' }).format(new Date());
    const items = [{ id: 'overview', label: 'Ringkasan', icon: 'grid' }];
    if (isRecorder()) items.push({ id: 'records', label: 'Catatan poin', icon: 'note' });
    if (role() === 'Guru BK') items.push({ id: 'reports', label: 'Laporan kesiswaan', icon: 'file' }, { id: 'letters', label: 'Surat panggilan', icon: 'mail' });
    if (role() === 'Wali Kelas') items.push({ id: 'class', label: 'Siswa di kelas', icon: 'users' });
    if (role() === 'Kesiswaan') items.push({ id: 'reports', label: 'Laporan masuk', icon: 'file' }, { id: 'statistics', label: 'Statistik sekolah', icon: 'chart' }, { id: 'letters', label: 'Surat panggilan', icon: 'mail' });
    if (role() === 'Siswa') items.push({ id: 'history', label: 'Riwayat saya', icon: 'clock' });
    items.push({ id: 'alerts', label: 'Peringatan', icon: 'bell' });
    $('#primary-nav').innerHTML = items.map((item) => `<a class="nav-item ${state.page === item.id ? 'active' : ''}" href="#${item.id}" data-nav="${item.id}"><svg><use href="#icon-${item.icon}"></use></svg><span>${item.label}</span><i class="nav-indicator"></i></a>`).join('');
    $('#page-breadcrumb').textContent = items.find((item) => item.id === state.page)?.label || 'Ringkasan';
}

async function loadPage() {
    const target = $('#page-content'); target.innerHTML = '<div class="loading-state"><span class="loading-mark"></span><strong>Memuat data</strong><span>Menyiapkan informasi terbaru...</span></div>';
    try { if (state.page === 'overview') return overview(target); if (state.page === 'records') return records(target); if (state.page === 'alerts') return alerts(target); if (state.page === 'class') return classRecap(target); if (state.page === 'history') return history(target); if (state.page === 'reports') return reports(target); if (state.page === 'statistics') return statistics(target); if (state.page === 'letters') return letters(target); } catch (error) { target.innerHTML = `<div class="empty-state"><span class="empty-icon"><svg><use href="#icon-alert"></use></svg></span><strong>Data belum dapat dimuat</strong><p>${escapeHtml(error.message)}</p><button class="button ghost" data-retry="true">Coba lagi</button></div>`; $('[data-retry]')?.addEventListener('click', loadPage); }
}

async function overview(target) {
    let stats = { total_poin_pelanggaran: 0, total_poin_apresiasi: 0, total_transaksi: 0, siswa_butuh_penanganan: 0 }, data = { data: [] }, intro = 'Pantau perkembangan dan tindak lanjut siswa dari satu ruang kerja.';
    if (role() === 'Kesiswaan') stats = await api('/statistik/overview'); else if (isRecorder()) data = await api('/catatan-poin?limit=5'); else if (role() === 'Siswa') stats = await api('/siswa/rekap'); else if (role() === 'Wali Kelas') data.data = await api('/kelas/rekap');
    target.innerHTML = pageIntro(role() === 'Siswa' ? 'RUANG SISWA' : 'OVERVIEW SEKOLAH', `Selamat datang, ${escapeHtml(state.user.nama_lengkap?.split(' ')[0] || 'Pengguna')}.`, intro, isRecorder() ? '<button class="button primary" data-open-record><svg><use href="#icon-plus"></use></svg> Catat kejadian</button>' : '') + statCards(stats, role()) + (isRecorder() ? recordTable(data.data || []) : role() === 'Wali Kelas' ? classTable(data.data || []) : quickPanels(role()));
    bindPageEvents();
}

function pageIntro(eyebrow, title, copy, action = '') { return `<div class="page-intro"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="muted">${copy}</p></div>${action}</div>`; }
function statCards(stats, currentRole) { return `<div class="stats-grid"><article class="stat-card coral"><span>Total pelanggaran</span><strong>${stats.total_poin_pelanggaran ?? 0}</strong><small>${currentRole === 'Siswa' ? 'poin yang tercatat' : 'poin terakumulasi'}</small><b class="stat-icon"><svg><use href="#icon-alert"></use></svg></b></article><article class="stat-card mint"><span>Total apresiasi</span><strong>${stats.total_poin_apresiasi ?? 0}</strong><small>poin positif</small><b class="stat-icon"><svg><use href="#icon-heart"></use></svg></b></article><article class="stat-card yellow"><span>Total transaksi</span><strong>${stats.total_transaksi ?? '-'}</strong><small>catatan tercatat</small><b class="stat-icon"><svg><use href="#icon-note"></use></svg></b></article><article class="stat-card navy"><span>Perlu penanganan</span><strong>${stats.siswa_butuh_penanganan ?? '-'}</strong><small>melewati ambang 25 poin</small><b class="stat-icon"><svg><use href="#icon-users"></use></svg></b></article></div>`; }
function recordTable(records = []) { return `<section class="panel"><div class="panel-heading"><div><p class="eyebrow">AKTIVITAS TERBARU</p><h3>Catatan poin terakhir</h3><p class="muted">Kejadian disiplin dan apresiasi yang baru masuk.</p></div><a class="text-link" href="#records">Lihat semua <svg><use href="#icon-arrow-right"></use></svg></a></div><div class="table-wrap"><table><thead><tr><th>Siswa</th><th>Jenis kejadian</th><th>Tanggal</th><th>Status</th><th>Poin</th></tr></thead><tbody>${records.length ? records.map(recordRow).join('') : emptyRow('Belum ada catatan poin.  Mulai dengan mencatat kejadian pertama.', 5)}</tbody></table></div></section>`; }
function recordRow(item) { const positive = item.kategori_poin?.jenis === 'apresiasi'; return `<tr><td><div class="person-cell"><span class="table-avatar">${escapeHtml((item.siswa?.user?.nama_lengkap || 'S').slice(0, 1))}</span><span><strong>${escapeHtml(item.siswa?.user?.nama_lengkap || 'Siswa')}</strong><small>${escapeHtml(item.siswa?.nisn || 'NISN belum tersedia')}</small></span></div></td><td><span class="type ${positive ? 'positive' : 'negative'}">${positive ? 'Apresiasi' : 'Pelanggaran'}</span><small class="cell-subtext">${escapeHtml(item.kategori_poin?.nama_kategori || '-')}</small></td><td>${item.tanggal ? new Date(item.tanggal).toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' }) : '-'}</td><td><span class="status-badge ${String(item.status_validasi || '').toLowerCase()}">${escapeHtml(item.status_validasi || '-')}</span></td><td><strong class="points ${positive ? 'positive-text' : 'negative-text'}">${positive ? '+' : '-'}${item.kategori_poin?.bobot_poin || 0}</strong></td></tr>`; }
function emptyRow(message, colspan) { return `<tr><td colspan="${colspan}" class="table-empty"><span class="empty-icon"><svg><use href="#icon-note"></use></svg></span>${message}</td></tr>`; }
function quickPanels(currentRole) { return `<div class="split-panels"><section class="panel accent-panel"><span class="eyebrow">ALUR POINKU</span><h3>Pantau kejadian sampai tindak lanjut.</h3><p>Setiap threshold yang terlewati akan membuat peringatan otomatis untuk tim yang berwenang.</p><a class="text-link" href="#alerts">Buka peringatan <svg><use href="#icon-arrow-right"></use></svg></a></section><section class="panel checklist-panel"><div class="panel-heading"><div><p class="eyebrow">STATUS SISTEM</p><h3>Ruang kerja ${escapeHtml(currentRole)}</h3></div><span class="live-dot">AKTIF</span></div><div class="check-row"><span><svg><use href="#icon-check"></use></svg></span><div><strong>Data tersinkronisasi</strong><small>Informasi terbaru siap dipantau.</small></div></div><div class="check-row"><span><svg><use href="#icon-check"></use></svg></span><div><strong>Threshold otomatis</strong><small>Peringatan dibuat saat saldo berubah.</small></div></div></section></div>`; }

async function records(target) { const data = await api('/catatan-poin?limit=20'); target.innerHTML = pageIntro('PENGELOLAAN KEJADIAN', 'Catatan poin', 'Kelola riwayat pelanggaran dan apresiasi siswa.', '<button class="button primary" data-open-record><svg><use href="#icon-plus"></use></svg> Catat kejadian</button>') + `<div class="toolbar"><div class="search-field"><svg><use href="#icon-search"></use></svg><input placeholder="Cari nama siswa atau kategori..." data-local-search></div><button class="button outline"><svg><use href="#icon-filter"></use></svg> Filter</button></div>` + recordTable(data.data || []); bindPageEvents(); }
async function classRecap(target) { const data = await api('/kelas/rekap'); target.innerHTML = pageIntro('MONITORING KELAS', 'Siswa di kelas', 'Pantau saldo poin dan perkembangan siswa yang menjadi tanggung jawab Anda.') + `<section class="panel">${panelHeading('Daftar siswa', 'Ringkasan poin seluruh siswa di kelas.')}<div class="table-wrap"><table><thead><tr><th>Siswa</th><th>Pelanggaran</th><th>Apresiasi</th><th>Saldo poin</th><th>Status</th></tr></thead><tbody>${data.length ? data.map((item) => `<tr><td><div class="person-cell"><span class="table-avatar">${escapeHtml(item.nama.slice(0, 1))}</span><span><strong>${escapeHtml(item.nama)}</strong><small>${escapeHtml(item.nisn || '-')} · ${escapeHtml(item.kelas || '')}</small></span></div></td><td class="negative-text">${item.total_poin_pelanggaran}</td><td class="positive-text">+${item.total_poin_apresiasi}</td><td><strong>${item.saldo_poin}</strong></td><td><span class="status-badge ${item.total_poin_pelanggaran >= 25 ? 'warning' : 'disetujui'}">${item.total_poin_pelanggaran >= 25 ? 'Perlu dipantau' : 'Normal'}</span></td></tr>`).join('') : emptyRow('Belum ada data siswa.', 5)}</tbody></table></div></section>`; }
async function history(target) { const data = await api('/siswa/riwayat?limit=20'); target.innerHTML = pageIntro('RIWAYAT PRIBADI', 'Riwayat poin saya', 'Lihat seluruh catatan kedisiplinan dan apresiasi yang tercatat.') + recordTable(data.data || []); }
async function alerts(target) { const result = await api('/notifikasi?limit=20'); const items = result.data || []; target.innerHTML = pageIntro('AUTOMATION CENTER', 'Peringatan aktif', 'Threshold yang terlewati akan muncul di sini secara otomatis.') + `<div class="alert-list">${items.length ? items.map((item) => `<article class="alert-card ${item.dibaca_pada ? 'read' : ''}"><span class="alert-icon"><svg><use href="#icon-alert"></use></svg></span><div><span class="eyebrow">${escapeHtml(item.siswa?.user?.nama_lengkap || 'Siswa')}</span><h3>${escapeHtml(item.judul)}</h3><p>${escapeHtml(item.pesan)}</p><small>${item.created_at ? new Date(item.created_at).toLocaleDateString('id-ID') : 'Baru saja'}</small></div><button class="button ghost" data-read="${item.id}">${item.dibaca_pada ? 'Sudah dibaca' : 'Tandai dibaca'}</button></article>`).join('') : '<div class="empty-state"><span class="empty-icon"><svg><use href="#icon-bell"></use></svg></span><strong>Belum ada peringatan</strong><p>Sistem akan membuat peringatan saat siswa melewati threshold.</p></div>'}</div>`; $$('[data-read]').forEach((button) => button.addEventListener('click', async () => { await api(`/notifikasi/${button.dataset.read}/read`, { method: 'PUT' }); loadPage(); })); }
async function reports(target) { const result = await api('/laporan?limit=20'); const items = result.data || []; target.innerHTML = pageIntro('TINJAUAN KESISWAAN', 'Laporan penanganan', 'Tinjau laporan Guru BK sebelum tindakan resmi diputuskan.') + `<section class="panel">${panelHeading('Laporan masuk', 'Daftar pengajuan yang menunggu keputusan.') }<div class="table-wrap"><table><thead><tr><th>Siswa</th><th>Jenis tindakan</th><th>Pengaju</th><th>Status</th><th>Diajukan</th></tr></thead><tbody>${items.length ? items.map((item) => `<tr><td><strong>${escapeHtml(item.siswa?.user?.nama_lengkap || 'Siswa')}</strong></td><td>${escapeHtml(item.jenis_tindakan)}</td><td>${escapeHtml(item.bk?.nama_lengkap || '-')}</td><td><span class="status-badge ${item.status}">${escapeHtml(item.status)}</span></td><td>${item.diajukan_pada ? new Date(item.diajukan_pada).toLocaleDateString('id-ID') : '-'}</td></tr>`).join('') : emptyRow('Belum ada laporan masuk.', 5)}</tbody></table></div></section>`; }
async function statistics(target) { const stats = await api('/statistik/overview'); target.innerHTML = pageIntro('INSIGHT SEKOLAH', 'Statistik sekolah', 'Baca pola kejadian untuk menentukan pendampingan yang lebih tepat.') + statCards(stats, role()) + quickPanels(role()); }
async function letters(target) { const result = await api('/surat-panggilan?limit=20'); const items = result.data || []; target.innerHTML = pageIntro('TINDAK LANJUT', 'Surat panggilan', 'Kelola draf surat dan status tindak lanjut orang tua.') + `<section class="panel">${panelHeading('Daftar surat', 'Draf otomatis dari threshold dan surat yang telah diproses.') }<div class="table-wrap"><table><thead><tr><th>Nomor surat</th><th>Siswa</th><th>Tanggal</th><th>Status</th><th>Total poin</th></tr></thead><tbody>${items.length ? items.map((item) => `<tr><td><strong>${escapeHtml(item.nomor_surat)}</strong></td><td>${escapeHtml(item.siswa?.user?.nama_lengkap || 'Siswa')}</td><td>${item.tanggal_surat ? new Date(item.tanggal_surat).toLocaleDateString('id-ID') : '-'}</td><td><span class="status-badge ${item.status}">${escapeHtml(item.status)}</span></td><td>${item.total_poin}</td></tr>`).join('') : emptyRow('Belum ada surat panggilan.', 5)}</tbody></table></div></section>`; }
function panelHeading(title, copy) { return `<div class="panel-heading"><div><p class="eyebrow">WORKSPACE</p><h3>${title}</h3><p class="muted">${copy}</p></div><span class="live-dot">LIVE</span></div>`; }

function openRecordModal() { $('#modal-root').innerHTML = `<div class="modal-backdrop"><form class="modal-card" id="record-form"><button type="button" class="modal-close" data-close-modal aria-label="Tutup"><svg><use href="#icon-close"></use></svg></button><p class="eyebrow">INPUT KEJADIAN</p><h2>Catat poin siswa</h2><p class="muted">Isi detail kejadian untuk membangun riwayat yang lengkap.</p><label>ID siswa<input name="siswa_id" type="number" required placeholder="Contoh: 12"></label><label>ID kategori poin<input name="kategori_poin_id" type="number" required placeholder="Contoh: 2"></label><div class="form-grid"><label>Tanggal<input name="tanggal" type="date" required value="${new Date().toISOString().slice(0, 10)}"></label><label>Status validasi<select name="status_validasi"><option value="${role() === 'Guru Pelapor' ? 'menunggu_validasi' : 'disetujui'}">${role() === 'Guru Pelapor' ? 'Menunggu validasi' : 'Disetujui'}</option><option value="draft">Simpan sebagai draf</option></select></label></div><label>Kronologi<textarea name="keterangan" required placeholder="Ceritakan kejadian secara objektif..."></textarea></label><div class="modal-actions"><button type="button" class="button outline" data-close-modal>Batal</button><button class="button primary" type="submit">Simpan catatan</button></div><p id="record-error" class="form-error"></p></form></div>`; $('[data-close-modal]').addEventListener('click', closeModal); $('#record-form').addEventListener('submit', async (event) => { event.preventDefault(); const error = $('#record-error'); try { await api('/catatan-poin', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); closeModal(); toast('Catatan poin berhasil disimpan.', 'success'); loadPage(); } catch (exception) { error.textContent = exception.message; } }); }
function closeModal() { $('#modal-root').innerHTML = ''; }
function toast(message, kind = 'info') { const item = document.createElement('div'); item.className = `toast ${kind}`; item.innerHTML = `<svg><use href="#icon-check"></use></svg>${escapeHtml(message)}`; $('#toast-region').append(item); setTimeout(() => item.remove(), 3500); }
function bindPageEvents() { $('[data-open-record]')?.addEventListener('click', openRecordModal); }
function bindEvents() { document.addEventListener('click', (event) => { const nav = event.target.closest('[data-nav]'); if (nav) { event.preventDefault(); state.page = nav.dataset.nav; location.hash = state.page; hydrateShell(); loadPage(); $('#sidebar').classList.remove('open'); } }); $('.menu-button')?.addEventListener('click', () => $('#sidebar').classList.add('open')); $('.sidebar-close, .sidebar-scrim')?.addEventListener('click', () => $('#sidebar').classList.remove('open')); $('#logout')?.addEventListener('click', () => logout()); $('.password-toggle')?.addEventListener('click', (event) => { const input = $('#password'); input.type = input.type === 'password' ? 'text' : 'password'; event.currentTarget.classList.toggle('active'); }); $('#login-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const error = $('#login-error'); error.textContent = ''; try { const data = await api('/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); state.token = data.token; state.user = data.user; state.page = 'overview'; localStorage.setItem('pointku_token', state.token); localStorage.setItem('pointku_user', JSON.stringify(state.user)); render(); } catch (exception) { error.textContent = exception.message; } }); }

bindEvents(); render();
