name: Belajar Workflow Pertama

on: 
  push: 
    branches: 
      - main

jobs: 
  nyobaan-we:
    runs-on: ubuntu-latest
    steps:
      - name: Hellow Wargi Tasik
        run: echo "Hello Wargi Tasik"