name: "Deploy to VPS Server"

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 202.155.13.142
          username: keyza
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/pointku.kezadev.my.id/POINTKU
            git pull origin main
            npm run build
